### PR TITLE
Supporting cassandra 3.x

### PR DESCRIPTION
**Pull request by masumsoft**
The travis ci checks will fail because the project is currently configured to test with cassandra 2.x in travis.

### CODE REVIEW

**Comment by masumsoft** [comment]
@jorgebay should I upgrade the travis.yml to fix the failed build or you would like to do that yourself?

**Comment by jorgebay** [comment]
Nice catch!

We should use driver method to get table metadata [getTable()](http://docs.datastax.com/en/drivers/nodejs/3.0/module-metadata-Metadata.html#getTable), that works for any Cassandra version, something like:
```javascript
client.metadata.getTable(keyspace, table, function (err, tableInfo) {
  if (err) return callback(err);
  if (tableInfo) {
    //table is already created
    self.schemaStatus.created = true;
    return callback();
  }
  //create the table
});
```

@masumsoft Do you want to adapt your pull requests to use the driver method?

**Comment by masumsoft** [comment]
@jorgebay I didn't know that metadata function existed. Thanks for the code example. Updated the PR and it's passing now.

**Comment by jorgebay** [comment]
Cool, I will squash them and merge!

**Comment by jorgebay** [comment]
Landed in 29ffc2744ae4f2c84b8aa9409ce41cc31345b491. Thanks!

**Comment by masumsoft** [comment]
@jorgebay Thanks, any chance of pushing this to npm?

**Comment by jorgebay** [comment]
Done!

**Pull request closed without merging**
